-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 20:55:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CURSOS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CURSOS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CURSOS` ;
USE `CURSOS` ;

-- -----------------------------------------------------
-- Table `CURSOS`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CURSOS`.`Profesor` (
  `id_profesor` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_profesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CURSOS`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CURSOS`.`Curso` (
  `id_curso` INT NOT NULL,
  `id_profesor` INT NULL,
  `nombre_curso` VARCHAR(45) NULL,
  `Profesor_id_profesor` INT NOT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_Curso_Profesor1_idx` (`Profesor_id_profesor` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_Profesor1`
    FOREIGN KEY (`Profesor_id_profesor`)
    REFERENCES `CURSOS`.`Profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CURSOS`.`Nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CURSOS`.`Nota` (
  `id_nota` INT NOT NULL,
  `id_curso` INT NULL,
  `nota` INT NULL,
  `Curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_nota`),
  INDEX `fk_Nota_Curso1_idx` (`Curso_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_Nota_Curso1`
    FOREIGN KEY (`Curso_id_curso`)
    REFERENCES `CURSOS`.`Curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CURSOS`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CURSOS`.`Estudiante` (
  `id_estudiante` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT 'pEstudiante',
  `edad` VARCHAR(45) NULL DEFAULT '1',
  `sexo` VARCHAR(45) NULL,
  `Nota_id_nota` INT NOT NULL,
  PRIMARY KEY (`id_estudiante`, `Nota_id_nota`),
  INDEX `fk_Estudiante_Nota_idx` (`Nota_id_nota` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_Nota`
    FOREIGN KEY (`Nota_id_nota`)
    REFERENCES `CURSOS`.`Nota` (`id_nota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
